# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/transcoder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/transcoder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/transcoder.proto\x12\ntranscoder\"i\n\x10VideoTaskRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x17\n\x0finput_file_path\x18\x02 \x01(\t\x12\x18\n\x10output_file_path\x18\x03 \x01(\t\x12\x12\n\nresolution\x18\x04 \x01(\t\"6\n\x12TaskStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2a\n\x11TranscoderService\x12L\n\x0cProcessVideo\x12\x1c.transcoder.VideoTaskRequest\x1a\x1e.transcoder.TaskStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transcoder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOTASKREQUEST']._serialized_start=38
  _globals['_VIDEOTASKREQUEST']._serialized_end=143
  _globals['_TASKSTATUSRESPONSE']._serialized_start=145
  _globals['_TASKSTATUSRESPONSE']._serialized_end=199
  _globals['_TRANSCODERSERVICE']._serialized_start=201
  _globals['_TRANSCODERSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
