# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import transcoder_pb2 as proto_dot_transcoder__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/transcoder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscoderServiceStub(object):
    """--- Definición del Servicio ---
    Esto es como definir la "clase" o el "menú de habilidades" de nuestro Worker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideo = channel.unary_unary(
                '/transcoder.TranscoderService/ProcessVideo',
                request_serializer=proto_dot_transcoder__pb2.VideoTaskRequest.SerializeToString,
                response_deserializer=proto_dot_transcoder__pb2.TaskStatusResponse.FromString,
                _registered_method=True)


class TranscoderServiceServicer(object):
    """--- Definición del Servicio ---
    Esto es como definir la "clase" o el "menú de habilidades" de nuestro Worker.
    """

    def ProcessVideo(self, request, context):
        """Define una función remota (RPC) llamada "ProcessVideo".
        Recibe un mensaje de tipo "VideoTaskRequest" y devuelve uno de tipo "TaskStatusResponse".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=proto_dot_transcoder__pb2.VideoTaskRequest.FromString,
                    response_serializer=proto_dot_transcoder__pb2.TaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcoder.TranscoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transcoder.TranscoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscoderService(object):
    """--- Definición del Servicio ---
    Esto es como definir la "clase" o el "menú de habilidades" de nuestro Worker.
    """

    @staticmethod
    def ProcessVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transcoder.TranscoderService/ProcessVideo',
            proto_dot_transcoder__pb2.VideoTaskRequest.SerializeToString,
            proto_dot_transcoder__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
